config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'welcome#index'

  devise_for :users

  resources :recipes
  resources :items
  resources :tools
  resources :categories
  resources :dictionaries, only: %i(index)
  namespace :my do
    resources :items, only: %i(index)
    put 'items' => "items#updates"
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :level, :name, :job_id, :kana, :ingredients_attributes
  belongs_to :job
  has_many :ingredients
  has_many :items, :through => :ingredients
  accepts_nested_attributes_for :ingredients, :reject_if => proc {|attributes| attributes['item_id'].blank?}, :allow_destroy => true

  validates :level,
    :presence     => true,
    :numericality => {
      :only_integer => true,
      :greater_than => 0
    }


end

app/controllers/recipes_controller.rb
# encoding: utf-8

class RecipesController < PageController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipe_list = []
    items = {}
    @item_list = []
    unless params[:recipes].blank?
      params[:recipes].each do |recipe|
        total = 0
        _ingredients = []
        Recipe.find_by_name(recipe).ingredients.each do |ingredient|
          total += ingredient.item.price * ingredient.number
          _ingredients << {:name => ingredient.item.name, :count => ingredient.number, :unitprice => ingredient.item.price }
          if items.has_key?(ingredient.item.kana)
            items[ingredient.item.kana] += ingredient.number
          else
            items[ingredient.item.kana] = ingredient.number
          end
        end
        @recipe_list << {:name => recipe, :price => total, :items => _ingredients}
      end
      items.sort.each do |item|
        @item_list << {:name => Item.find_by_kana(item[0]).name, :count => item[1], :cost => Item.find_by_kana(item[0]).price * item[1] }
      end
    end
      respond_to do |format|
      format.html # index.html.erb
      format.json {

        result_hash = {
          :recipe_list => @recipe_list,
          :item_list => @item_list }

        render json: result_hash
      }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    @ingredients = Array.new(5) {Ingredient.new}
    @items = Item.scoped.map{|item| [item.name, item.id]}.sort
    @categories = Category.scoped.map{|category| [category.name, category.id]}.sort
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
    @ingredients = Ingredient.where(:recipe_id => params[:id])
#    if @ingredients.count < 5
#      @ingredients << Array.new(5-@ingredients.count) {Ingredient.new}
#    end
    @items = Item.scoped.map{|item| [item.name, item.id]}.sort
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def add_ingredient_link(name)
    link_to_function name do |page|
      page.insert_html :bottom, :ingredients, :partial => 'ingredient', :object => Ingredient.new
    end
  end

end

app/views/recipes/_form.html.erb
<%= form_for(@recipe, :html => {:class => 'form-horizontal'} ) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kana, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :kana %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :level, :class => "control-label" %>
    <div class="controls">
      <%= f.number_field :level, :min => 1 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :job, :class => "control-label" %>
    <div class="controls">
<% Job.all.each do |job| %>
      <label class="radio radio-job" class="control-label">
        <%= f.radio_button :job_id, job.id, {} %>
        <%= job.name %>
      </label>
<% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :items, :class => "control-label" %>
    <table class="controls">
  <% @ingredients.each do |ingredient| %>
      <tr>
    <%= f.fields_for "ingredients_attributes[]", ingredient do |field| %>
      <% if ingredient.persisted? %>
        <%= field.hidden_field(:id, value: ingredient.id) %>
        削除<%= field.check_box :_destroy %>
      <% end %>
        <td><%= field.select :item_id, @items, :include_blank => true %></td>
        <td><%= field.number_field :number, :min => 1, :max => 50, :class => 'input-mini' %></td>
    <% end %>
  <% end %>
      </tr>
    </table>
  </div>

  <% Category.all.each do |category| %>
  <label>
  <%=f.check_box :category_ids, {:checked => @recipe.categories.include?(category), :name => "recipe[category_ids][]"}, category.id, "" %>
  <%= category.name %><br/></label>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% content_for :head do %>
<style>
  .radio { float : left; }
  .control-group { clear: both; }
  .radio-job { 
    padding-top : 3px !important;
    padding-bottom : 5px;
    height   : 1.3em;
    line-height : 1.5em;
    width   : 3.5em;
    margin-right : 1em;
    border   : solid 1px gray;
    border-radius : 5px;
  } 
</style>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<p>
  <%= form_for(:recipes, :method => :get, :html => { :class => "form-search"}) do |f| %>
  <%= label_tag :keyword, "素材名" %>
  <%= text_field_tag :keyword, '', :class => "span12 search-query", :autofocus => "autofocus", "data-provide" => "typeahead" %>
  <%= label_tag :number, "数量" %>
  <%= text_field_tag :number %>
  <%= f.submit "設定", :class => "btn" %>
  <% end %>
</p>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<% content_for :content do %>
  <div id="recipe_finder"></div>


  <script type="text/template" id="tmpl-recipe_table">
    <div id="recipe_materials" style="display:none;">
      <section>
        <h2>レシピリスト</h2>
        <table id="recipe_list_table" class="table">
        </table>
      </section>

      <section>
        <h2>必要素材</h2>
        <table id="material_list_table" class="table">
        </table>
      </section>
    </div>
    <div id="default_contents" class="alert alert-info" style="display:none;">
      レシピを検索して必要な素材とお店で素材を買った時の値段をチェック！<br>
      レシピを続けて検索すると、必要な素材の合計数も出るので職人の依頼に便利です。<br>
    </div>
  </script>


  <script type="text/template" id="tmpl-recipe_list_table">
    <table>
      <thead>
        <tr>
          <th class="recipe_name">レシピ名</th>
          <th class="recipe_cost">原価合計 <small>（バザー除く）</small></th>
          <th class="recipe_buttons"><a href="/recipes" class="btn btn-small btn-inverse all_remove_button" style="color:white"><i class="icon-remove"></i><span class="recipes_all_remove_button_text"> 全削除</span></a></th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </script>


  <script type="text/template" id="tmpl-material_list_table">
    <table>
      <thead>
        <tr>
          <th>アイテム名</th>
          <th class="material_count">合計必要数</th>
          <th class="material_price">購入金額</th>
          <td class="material_button"></td>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </script>

<% end %>

<% content_for :javascripts do %>
    <%#= javascript_include_tag "recipes" %>
    <script>
      function recipes_callback() {
<%- if user_signed_in? -%>
<%-   unless current_user.admin? -%>
       $(".recipes-action").append("");
<%-   end -%>
<%- end -%>
    }
    </script>
<% end %>

app/views/recipes/new.html.erb
<% content_for :content do %>
  <p>下記の必要項目を入力し、[新しくレシピを追加する]ボタンを押してください</p>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>
<% end %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<p>
  <b>Level:</b>
  <%= @recipe.level %>
</p>
  <% @recipe.ingredients.each do |ingredient| %>
    <%= ingredient.item.name %>
    <%= ingredient.number %><br>
  <% end %>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>