config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'welcome#index'

  devise_for :users

  resources :recipes
  resources :items
  resources :tools
  resources :categories
  resources :dictionaries, only: %i(index)
  namespace :my do
    resources :items, only: %i(index)
    put 'items' => "items#updates"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  #attr_accessible :name, :price, :kana
  has_many :ingredients
  has_many :recipes, :through => :ingredients
  has_many :inventories
  has_many :users, :through => :inventories


  def to_s
    self.attributes.to_s
  end

  def jobs
    recipes.map(&:job).uniq
  end

  def to_dictionary_hash
    {
      name: name,
      kana: kana,
      type: 'item'
    }
  end
end

app/controllers/items_controller.rb
class ItemsController < PageController
  # GET /items
  # GET /items.json
  def index
    history = (cookies[:keyword].nil? || cookies[:keyword].empty?) ? [] : JSON.parse(cookies[:keyword])
    @cookie_history = []
    @items = []
    unless params[:keyword].blank?
      @items = Item.where('name LIKE ?', '%'+params[:keyword]+'%')
      if @items.count == 1
        @item = @items.first 
        history.delete_if { |x| x["i"] == @item.id || Time.at(x["d"]) < (Time.now - 24.hours) }
        @cookie_history = history
        history.unshift( { "i" => @item.id, "d" => Time.now.to_i } )
      else
        @cookie_history = history
      end
    end
    cookies[:keyword] = history.to_json
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/my/items_controller.rb
# encoding: utf-8


# 在庫管理用コントローラ
#
# @since 2.0.0
#
class My::ItemsController < MyController

  before_filter :parse_equipments_items_json, :only => [:updates]

  # 在庫情報一覧
  #
  # @example 在庫情報確認ページ
  # +GET /my/items(.html)
  # +
  # +render 'Rails.root/app/view/my/items/index.html.erb'
  #
  # @example 在庫情報取得API
  # +GET /my/items.json
  # +
  # +{
  # ++"uid": "547118FF172E4BFD9D3881A83EA79B62",
  # ++"equipments": [
  # +++{
  # ++++"recipe_name": "どうのつるぎ",
  # ++++"recipe_kana": "どうのつるぎ",
  # ++++"cost": 320,
  # ++++"renkin_count": 1
  # +++},
  # +++{
  # ++++"recipe_name": "銅のさいほう針",
  # ++++"recipe_kana": "どうのさいほうばり",
  # ++++"cost": 20,
  # ++++"renkin_count": 0,
  # +++}
  # ++],
  # ++"items": [
  # +++{
  # ++++"name": "どうのこうせき",
  # ++++"kana": "どうのこうせき",
  # ++++"cost": 30,
  # ++++"stock":2
  # +++},
  # +++{
  # ++++"name": "じょうぶな枝",
  # ++++"kana": "じょうぶなえだ",
  # ++++"cost": 40,
  # ++++"stock":1
  # +++},
  # +++{
  # ++++"name": "汗と涙の結晶",
  # ++++"kana": "あせとなみだのけっしょう",
  # ++++"cost": 0,
  # ++++"stock":20
  # +++}
  # ++]
  # +}
  #
  # @todo resultの中身作る
  def index

    @uid = Digest::SHA1.hexdigest("user-#{current_user.id}")

    @items = []
    resources.each do |item|
      i = Item.find(item.item_id)
      @items << {:name => i.name,  :kana => i.kana, :stock => item.stock, :cost => (item.total_cost/item.stock rescue 0)}
    end
    @equipments = []
    my_equipments.each do |equipment|
      recipe = Recipe.find(equipment.recipe_id)
      @equipments << {:recipe_name => recipe.name, :recipe_kana => recipe.kana, :cost => equipment.cost, :renkin_count => equipment.renkin_count }
    end

    @result = { uid: @uid, equipments: @equipments, items: @items }

    respond_to do |format|
      format.html
      format.json { render json: @result }
    end
  end


  # 在庫情報更新
  #
  # @param [Hash] params リクエストパラメータ
  # @option params [Hash] equipments 装備品の変更情報を含んだ配列もどき
  # @option equipments [Hash] /\d+/ 変更順をキーとする装備品の在庫変更情報
  # @option /\d+/ [String] name 変更対象の装備品名
  # @option /\d+/ [String] stock 在庫の変動(1|-1)
  # @option /\d+/ [String] renkin_count 錬金済回数
  # @option /\d+/ [String] cost 装備品のコスト
  # @option params [Hash] items アイテムの変更情報を含んだ配列もどき
  # @option items [Hash] /\d+/ 変更順をキーとするアイテムの在庫変更情報
  # @option /\d+/ [String] name 変更対象のアイテム名
  # @option /\d+/ [String] stock 在庫の変動数
  # @option /\d+/ [String] cost アイテムのコスト
  # @return [String] 変更されたデータの情報を含むJSONオブジェクト（例参照）
  #
  # @note before_filter :parse_equipments_items_jsonにより、パラメータは@requested_equipments_itemsに解析され、格納される。
  # @see #parse_equipments_items_json
  #
  # @todo parse_equipments_items_jsonが処理した@requested_equipments_itemsを、ごにょごにょして@resultに入れる
  #
  # @example sd1 裁縫職人が初級魔法戦士服を作って登録する。コットン草は使い切る。
  # +RequestParams:
  # ++{
  # +++"equipments" => {
  # ++++"0" => { "name" => "初級魔法戦士服", "stock" => "1", "renkin_count" => "0", "cost" => "1260" }
  # +++},
  # +++"items" => {
  # ++++"0" => { "name" => "あやかしそう", "stock" => "-3" },
  # ++++"1" => { "name" => "コットン草",   "stock" => "-3" }
  # +++}
  # ++}
  # +
  # +Response:
  # ++{
  # +++"equipments": [
  # ++++{ "name": "初級魔法戦士服", "stock": 1, "renkin_count": 0, "cost": 1260 }
  # +++],
  # +++"items": [
  # ++++{ "name": "あやかしそう", "stock": 7, "cost": 290 },
  # ++++{ "name": "コットン草", "stock": 0, "cost": 120 }
  # +++]
  # ++}
  #
  # @example sd2 ツボ職人がぬすっとの服＋１にしゅび力＋２の効果を付けて登録する。
  # +RequestParams:
  # ++{
  # +++"equipments" => {
  # ++++"0" => { "name" => "ぬすっとの服", "stock" => "-1", "renkin_count" => "1", cost" => "700" },
  # ++++"1" => { "name" => "ぬすっとの服", "stock" => "1",  "renkin_count" => "2", "cost" => "1000" }
  # +++},
  # +++"items" => {
  # ++++"0" => { "name" => "小さなこうら", "stock" => "-1" },
  # ++++"1" => { "name" => "ようせいの粉", "stock" => "-1" }
  # +++}
  # ++}
  # +
  # +Response:
  # ++{
  # +++"equipments": [
  # ++++{ "name": "ぬすっとの服", "stock": 0, "renkin_count": 1, cost": 700 },
  # ++++{ "name": "ぬすっとの服", "stock": 1,  "renkin_count": 2, "cost": 1000 }
  # +++],
  # +++"items": [
  # ++++{ "name": "小さなこうら", "stock": 2, "cost": 250  },
  # ++++{ "name": "ようせいの粉", "stock": 3, "cost": 100  }
  # +++]
  # ++}
  #
  #
  def updates

    ActiveRecord::Base.transaction do

    #input sample:
    #{:equipments => [{ :name => "麻の服", :stock => 1, :renkin_count => 0, :cost => 1260 }],
    # :items => [{ :name => "あやかしそう", :stock => 3, :cost => 300 },{ :name => "コットン草", :stock => 3, :cost => 600 }]}
    #
    #

    equipment_result = []
    if @requested_equipments_items[:equipments].present?
      @requested_equipments_items[:equipments].each do |equipment|
        case equipment[:stock]
          when 1
            my_equipments.create(:recipe_id => Recipe.find_by_name(equipment[:name]).id, 
                                 :cost => equipment[:cost],
                                 :renkin_count => equipment[:renkin_count])
          when -1
            my_equipments.find_by_recipe_id_and_cost_and_renkin_count(Recipe.find_by_name(equipment[:name]),equipment[:cost], equipment[:renkin_count]).destroy
            equipment[:stock] = 0
        end
        equipment_result << equipment
      end
    end

    item_result = []
    if @requested_equipments_items[:items].present?
      @requested_equipments_items[:items].each do |item|
        update_item = resources.where(:item_id => Item.find_by_name(item[:name]).id).first_or_create
        update_item.total_cost += item[:cost] || ((update_item.total_cost / update_item.stock) rescue 0) * item[:stock]
        update_item.stock += item[:stock]
          if update_item.stock > 0
            update_item.save
          else
            update_item.destroy
          end
        update_item = resources.try(:find_by_item_id, Item.find_by_name(item[:name]).id)
        item_result << {:name => item[:name], :stock => update_item.try(:stock) || 0, :cost => ((update_item.try(:total_cost) || 0) / (update_item.try(:stock) || 0) rescue 0 )}
      end
    end

    logger.debug @requested_equipments_items
    @result = {:equipments => equipment_result, :items => item_result }

    respond_to do |format|
      format.json { render json: @result }
    end
  end
end

  private

    # リクエストパラメータを最適化し、@requested_equipments_itemsへ格納する
    #
    # @param [Hash] params リクエストパラメータ
    # @option params [Hash] equipments 装備品の変更情報を含んだ配列もどき
    # @option equipments [Hash] /\d+/ 変更順をキーとする装備品の在庫変更情報
    # @option /\d+/ [String] name 変更対象の装備品名
    # @option /\d+/ [String] stock 在庫の変動(1|-1)
    # @option /\d+/ [String] renkin_count 錬金済回数
    # @option /\d+/ [String] cost 装備品のコスト
    # @option params [Hash] items アイテムの変更情報を含んだ配列もどき
    # @option items [Hash] /\d+/ 変更順をキーとするアイテムの在庫変更情報
    # @option /\d+/ [String] name 変更対象のアイテム名
    # @option /\d+/ [String] stock 在庫の変動数
    # @option /\d+/ [String] cost アイテムのコスト
    # @return [Hash] 最適化されたHashオブジェクト（例参照）
    #
    # @example sd1 裁縫職人が初級魔法戦士服を作って登録する。コットン草は使い切る。
    # +RequestParams:
    # ++{
    # +++"equipments" => {
    # ++++"0" => { "name" => "初級魔法戦士服", "stock" => "1", "renkin_count" => "0", "cost" => "1260" }
    # +++},
    # +++"items" => {
    # ++++"0" => { "name" => "あやかしそう", "stock" => "-3" },
    # ++++"1" => { "name" => "コットン草",   "stock" => "-3" }
    # +++}
    # ++}
    # +
    # +Result:
    # ++@requested_equipments_items = {
    # +++equipments: [
    # ++++{ name: "初級魔法戦士服", stock: 1, renkin_count: 0, cost: 1260 }
    # +++],
    # +++items: [
    # ++++{ name: "あやかしそう", stock: -3 },
    # ++++{ name: "コットン草", stock: -3 }
    # +++]
    # ++}
    #
    # @example sd2 ツボ職人がぬすっとの服＋１にしゅび力＋２の効果を付けて登録する。
    # +RequestParams:
    # ++{
    # +++"equipments" => {
    # ++++"0" => { "name" => "ぬすっとの服", "stock" => "-1", "renkin_count" => "1", cost" => "700" },
    # ++++"1" => { "name" => "ぬすっとの服", "stock" => "1",  "renkin_count" => "2", "cost" => "1000" }
    # +++},
    # +++"items" => {
    # ++++"0" => { "name" => "小さなこうら", "stock" => "-1" },
    # ++++"1" => { "name" => "ようせいの粉", "stock" => "-1" }
    # +++}
    # ++}
    # +
    # +Result:
    # ++@requested_equipments_items = {
    # +++equipments: [
    # ++++{ name: "ぬすっとの服", stock: -1, renkin_count: 1, cost: 700 },
    # ++++{ name: "ぬすっとの服", stock: 1,  renkin_count: 2, cost: 1000 }
    # +++],
    # +++items: [
    # ++++{ name: "小さなこうら", stock: -1 },
    # ++++{ name: "ようせいの粉", stock: -1 }
    # +++]
    # ++}
    #
    #
    def parse_equipments_items_json
      @requested_equipments_items ||= begin
        _equipments_items_hash = ['items','equipments'].each_with_object({}) { |key, hash|
          next unless params[key].kind_of? Hash
          hash[key.to_sym] = Array.new
          params[key].each do |no,value|
            hash[key.to_sym][no.to_i] = value.each_with_object({}) { |set,hash|
              hash[set[0].to_sym] = set[0] == "name" ? set[1] : set[1].to_i
            }
          end
        }
      end
    end

    def resources
      resources = Inventory.where(:user_id => current_user.id)
    end

    def my_equipments
      my_equipments = Equipment.where(:user_id => current_user.id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <%= f.label :kana %><br />
    <%= f.text_field :kana %>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% content_for :javascripts do %>
      <script>
              var itemList    = <%= Item.all.map(&:name).sort.to_s.html_safe %>;
                    var recipesList = <%= Recipe.all.map(&:name).sort.to_s.html_safe %>;
                        </script>
                      <% end %>

<% content_for :content do %>
<%= form_for(Item.new, method: :get, html: { class: 'form-inline', role: 'form' }) do |f| %>
  <div class="form-group">
    <%= text_field_tag :keyword,
          '',
          :autocomplete  => "off",
          :placeholder   => "素材名を入力",
          :class         => "form-control",
          :autofocus     => "autofocus",
          "data-provide" => "typeahead"  %>
  </div>
  <%= button_tag class: "btn btn-primary btn-lg" do %>
    検索
  <% end %>
<% end %>
<style>
h1 {
  font-size   : 20px;
  line-height   : 20px;
  margin     : 30px 0px 5px;
}

.item-list li {
  font-size   : 20px;
  line-height   : 30px;

}
#keyword {
  width: 216px;
  height: 45px;
}
.form-group {
  display: inline-block;
  margin: 0px;
  vertical-align: bottom;
}
form#new_item {
  text-align: center;
}
</style>
<% if @item %>
<h1><%= @item.name %>を含むレシピ</h1>
<div class="tabbable job_tabs">
  <ul class="nav nav-pills">
<%   Job.all.each_with_index do |job,i| %>
<%     @job_classes = ["job_tab#{i}"] %>
<%     @job_classes << "disabled" unless @item.jobs.include? job %>
    <li class="<%= @job_classes.join(" ") %>">
      <a href="#job<%= job.id %>" <%= 'data-toggle="tab"'.html_safe unless @job_classes.include? "disabled" %>>
        <%= job.name %>
<% unless @job_classes.include? "disabled" %>
<span class="badge"><%= @item.recipes.where(:job_id => job.id).count %></span>
<% end %>
      </a>
    </li>
<%   end %>
  </ul>


  <div class="tab-content">
<%   @item.jobs.each do |job| %>
    <div class="tab-pane <%= "active" if job.id == 1 %>" id="job<%= job.id %>">
      <table class="table">
        <tr>
          <th><%= Recipe.human_attribute_name(:name) %></th>
          <th><%= Recipe.human_attribute_name(:level) %></th>
        </tr>
<%     @item.recipes.where(:job_id => job.id).order("level ASC").each do |recipe| %>
        <tr>
          <td><%= recipe.name %></td>
          <td><%= recipe.level %></td>
        </tr>
<%     end %>
      </table>
      <br />
    </div>
<%   end %>

  </div>
</div>
<% elsif @items.empty? && !params[:keyword].nil? %>
<p>該当する素材がみつかりませんでした</p>
<% elsif @items && !params[:keyword].nil? %>
<p>複数の素材が該当しました。下記のなかからレシピを確認したいアイテムを選択してください</p>
<div class="item-list">
<ul class="nav nav-tabs nav-stacked">
<% @items.each do |item| %>
  <li><%= link_to item.name, items_path(:keyword => item.name) %></li>
<% end %>
</ul>
</div>
<% else %>
<p>素材名を入力して使う職人とレシピをチェックしよう！</p>
<p>*データが間違ってるかもしれません。お気づきの場合は<a href='http://twitter.com/gyakubiki_dqx'>@gyakubiki_dqx</a>までご一報ください。</p>
<% end %>

<% end %>


<% content_for :sidebar do %>
<ul class="histories">
<%   @cookie_history.each do |history| %>
<%     item = Item.find(history["i"]) %>
<%= link_to items_path(:keyword => item.name) do %>
<li>
<article>
<h2><%= item.name %></h2>
<ul class="job_markers clearfix">
<%     Job.all.each_with_index do |job,i| %>
<%       @job_classes = ["label", "job_marker#{i}"] %>
<%       @job_classes << "disabled" unless item.jobs.include? job %>
  <li class="<%= @job_classes.join(" ") %>"><%= job.name[0] %></li>
<%     end %>
</ul>
</article>
</li>
<%   end %>
<% end %>
</ul>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>