config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'welcome#index'

  devise_for :users

  resources :recipes
  resources :items
  resources :tools
  resources :categories
  resources :dictionaries, only: %i(index)
  namespace :my do
    resources :items, only: %i(index)
    put 'items' => "items#updates"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="google" value="notranslate">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="素材名を入力して使う職人とレシピをチェックしよう！">
    <title><%= content_for?(:title) ? yield(:title) : t("app_name") %></title>
    <%= render "commons/favicon_links" %>
    <%= render "commons/google_analytics" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= yield(:head) if content_for?(:head) %>
    <%= yield(:javascripts) if content_for?(:javascripts) %>

  </head>
  <body>

<%= render "commons/global_header" %>
<%= content_for?(:contents) ? yield(:contents) :yield %>

  </body>
</html>

app/views/layouts/devise.html.erb
<% content_for :head do %>
<% end %>
<% content_for :contents do %>
<%=  content_for?(:content) ? yield(:content) : yield %>
<%= render "commons/global_footer" %>
<% end %>
<%= render :file => 'layouts/application' %>

app/views/layouts/page.html.erb
<% content_for :head do %>
<% end %>
<% content_for :contents do %>
  <div id="global-navigation">
    <ul class="nav nav-pills">

      <%= content_tag :li,
        class: controller.is_a?(ItemsController) ? [:active] : [] do %>
        <%=   link_to items_path do %>
          <i class="fa fa-leaf fa-lg"></i>
          <span class="global-navigation-text"> 素材辞典</span>
        <% end %>
      <% end %>

      <%= content_tag :li,
        class: controller.is_a?(RecipesController) ? [:active] : [] do %>
        <%= link_to recipes_path do %>
          <i class="fa fa-book fa-lg"></i>
          <span class="global-navigation-text"> レシピ帳</span>
        <% end %>
      <%  end %>

<%- if user_signed_in? -%>
      <%= content_tag :li,
        class: controller.is_a?(My::ItemsController) ? [:active] : [] do %>
        <%= link_to my_items_path do %>
          <i class="fa fa-th-list fa-lg"></i> 在庫管理
        <% end %>
      <%  end %>

<%-   if current_user.admin? -%>
      <%= content_tag :li do %>
        <%= link_to admin_dashboard_path do %>
          <i class="fa fa-th-list fa-lg"></i>
          管理
        <% end %>
      <%  end %>
<%-   end -%>
<%- end -%>
    </ul>

  </div>

    <div class="container">
      <div class="content">
        <div class="row-fluid">
          <div class="span8" id="main-content">
<%= content_for?(:content) ? yield(:content) : yield %>
          </div>
          <div class="span4" id="aside-content">
<% if content_for?(:sidebar) %>
            <div class="well sidebar-nav">
<%= yield(:sidebar) %>
            </div>
<% end %>
<%= render "commons/amazon_affiliate" %>
          </div>
        </div><!--/row-->
      </div><!--/content-->

      <%= render "commons/global_footer" %>

    </div> <!-- /container -->

<% end %>
<%= render :file => 'layouts/application' %>